import 'config.dart';

const appLang = {
  'name': {'en': 'Anabond', 'ta': ''},
  'loginBtn': {'en': 'LOGIN', 'ta': ''},
  'userEmail': {'en': 'Username', 'ta': ''},
  'userEmailId': {'en': 'Email ID', 'ta': ''},
  'userPassword': {'en': 'Password', 'ta': ''},
  'loginbtstrip': {'en': 'Ask Support', 'ta': ''},
  'loginError': {'en': 'Incorrect username or password', 'ta': ''},
  'overViewTitle': {'en': 'Overview', 'ta': ''},
  // 'username': {'en': 'Dinesh Kumar', 'ta': ''},
  'myResponseHeading': {'en': 'My Responsibilities', 'ta': ''},
  'divResponseHeading': {'en': 'Division Responsibilities', 'ta': ''},
  'descriptionTitle': {'en': 'Description', 'ta': ''},
  'performanceTitle': {'en': 'Corresponding Performance Factor', 'ta': ''},
  'assignedTitle': {'en': 'Assigned Employees', 'ta': ''},
  'assignedShortTitle': {'en': 'Assigned Emp.', 'ta': ''},
  'performanceShortTitle': {'en': 'P.Factors', 'ta': ''},
  'searchbarTitle': {'en': 'Conduct meeting', 'ta': ''},
  'scopeTitle': {'en': 'Scope', 'ta': ''},
  'organisationTitle': {'en': 'Organisation', 'ta': ''},
  'divisionTitle': {'en': 'Division', 'ta': ''},
  'locationTitle': {'en': 'Location', 'ta': ''},
  'notificationTitle': {'en': 'Notification', 'ta': ''},
  'clearData': {'en': 'Clear all', 'ta': ''},
  'applybtn': {'en': 'Apply', 'ta': ''},
  'userLoginHead': {'en': 'Account info', 'ta': ''},
  'userName': {'en': 'Name', 'ta': ''},
  'userTeamRoll': {'en': 'Division', 'ta': ''},
  'userDesignation': {'en': 'Designation', 'ta': ''},
  'userMobileNo': {'en': 'Phone No', 'ta': ''},
  'userLogout': {'en': 'Logout', 'ta': ''},
  'userProfile': {'en': 'My Profile', 'ta': ''},
  'themeTitle': {'en': 'Background Theme', 'ta': ''},
  'organizationCompany01': {'en': 'ANA ITQ', 'ta': ''},
  'organizationCompany02': {'en': 'ANABOND', 'ta': ''},
  'organizationTitle': {'en': 'Choose Organization', 'ta': ''},
  'NoEmployee': {'en': 'No assigned employees', 'ta': ''},
};
// String getLang(String key) =>
//     (appLang[key] == null ? '' : appLang[key][appConfig['defaltLang']]);
